runtime: nodejs14
instance_class: F1
service: default
automatic_scaling:
  max_instances: 1
handlers:
  - url: .*
    script: auto
env_variables:
  DATABASE_URL: "postgresql://<USERNAME>:<PASSWORD>@localhost:5432/DBNAME?schema=public&host=/cloudsql/<CLOUD SQL INSTANCE NAME"
  JWT_ACCESS_SECRET: <SECRET>
  JWT_REFRESH_SECRET: <Another-SECRET>

